FROM golang:1.10.3-alpine@sha256:499b775c0954ce029c9db806c4543524b38eeb38bc5588c3ea81bb135f8c55db AS builder

RUN apk -U add git wget ca-certificates

RUN \
  wget -O /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && \
  chmod +x /usr/local/bin/dep

ENV CGO_ENABLED=0
ENV GOOS=linux GOARCH=arm GOARM=6
ENV VERSION=1.0
ENV GIT_COMMIT=5731b98a8aa2780afb03e47d3dabfb385ba58151

RUN \
  git clone https://github.com/weaveworks/kured.git /go/src/github.com/weaveworks/kured && \
  cd /go/src/github.com/weaveworks/kured && git checkout $GIT_COMMIT

RUN cd /go/src/github.com/weaveworks/kured && dep ensure
RUN go build -ldflags "-s -X main.version=$VERSION-$(echo $GIT_COMMIT | cut -c -8)" -o /kured github.com/weaveworks/kured/cmd/kured

FROM alpine@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0 AS fetcher

RUN apk -U add wget ca-certificates
RUN \
 wget -O /kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/arm/kubectl && \
 chmod +x /kubectl

COPY systemctl.sh /tmp
RUN install -m 0755 -o root -g root /tmp/systemctl.sh /bin/systemctl

FROM arm32v6/alpine:3.8@sha256:dabea2944dcc2b86482b4f0b0fb62da80e0673e900c46c0e03b45919881a5d84 AS alpine-armhf

FROM alpine:3.8@sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14 AS cross-fetch

RUN \
 mkdir /target && \
 mkdir -p /target/etc/apk && \
 cp /etc/apk/repositories /target/etc/apk/

# Alpine signing keys vary by architecture
COPY --from=alpine-armhf /etc/apk/keys/* /etc/apk/keys/

RUN \
 apk --root /target -U --keys-dir /etc/apk/keys add --arch armhf --initdb --no-script \
 dbus

FROM arm32v6/alpine:3.8@sha256:dabea2944dcc2b86482b4f0b0fb62da80e0673e900c46c0e03b45919881a5d84
COPY --from=fetcher /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=fetcher /kubectl /usr/bin/
COPY --from=cross-fetch /target/usr/lib/libdbus-1.so.3 /usr/lib/
COPY --from=cross-fetch /target/usr/bin/dbus-send /usr/bin/
COPY --from=fetcher /bin/systemctl /bin/
COPY --from=builder /kured /usr/bin/

ENTRYPOINT ["/usr/bin/kured"]
