FROM golang:1.16.7-alpine@sha256:3e6a2def9a57f23344a75bd71d9cd79726f0fbaf4b75330be5669773df0e9d4c AS builder

RUN apk -U add git wget ca-certificates

RUN \
  wget -O /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && \
  chmod +x /usr/local/bin/dep

ENV CGO_ENABLED=0
ENV GOOS=linux GOARCH=arm GOARM=6
ENV VERSION=1.0
ENV GIT_COMMIT=5731b98a8aa2780afb03e47d3dabfb385ba58151

RUN \
  git clone https://github.com/weaveworks/kured.git /go/src/github.com/weaveworks/kured && \
  cd /go/src/github.com/weaveworks/kured && git checkout $GIT_COMMIT

RUN cd /go/src/github.com/weaveworks/kured && dep ensure
RUN go build -ldflags "-s -X main.version=$VERSION-$(echo $GIT_COMMIT | cut -c -8)" -o /kured github.com/weaveworks/kured/cmd/kured

FROM alpine@sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae AS fetcher

RUN apk -U add wget ca-certificates
RUN \
 wget -O /kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/arm/kubectl && \
 chmod +x /kubectl

COPY systemctl.sh /tmp
RUN install -m 0755 -o root -g root /tmp/systemctl.sh /bin/systemctl

FROM arm32v6/alpine:3.14@sha256:1f66b8f3041ef8575260056dedd437ed94e7bfeea142ee39ff0d795f94ff2287 AS alpine-armhf

FROM alpine:3.14@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a AS cross-fetch

RUN \
 mkdir /target && \
 mkdir -p /target/etc/apk && \
 cp /etc/apk/repositories /target/etc/apk/

# Alpine signing keys vary by architecture
COPY --from=alpine-armhf /etc/apk/keys/* /etc/apk/keys/

RUN \
 apk --root /target -U --keys-dir /etc/apk/keys add --arch armhf --initdb --no-script \
 dbus

FROM arm32v6/alpine:3.14@sha256:1f66b8f3041ef8575260056dedd437ed94e7bfeea142ee39ff0d795f94ff2287
COPY --from=fetcher /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=fetcher /kubectl /usr/bin/
COPY --from=cross-fetch /target/usr/lib/libdbus-1.so.3 /usr/lib/
COPY --from=cross-fetch /target/usr/bin/dbus-send /usr/bin/
COPY --from=fetcher /bin/systemctl /bin/
COPY --from=builder /kured /usr/bin/

ENTRYPOINT ["/usr/bin/kured"]
